name: Trigger Webhook

on:
  push:

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to local server
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Sending webhook to $WEBHOOK_URL"
          curl -X POST $WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d '{"repository": {"full_name": "test/repo"}, "action": "test_event", "sender": {"login": "tester"}}'
